/**
 * Lưu ý : giữ nguyên thứ tự enum để tránh ảnh hưởng tới việc hiển thị
 */
export enum Roles {
    //Phe dân
    VILLAGER,
    LYCAN,
    ANGEL,
    CUPID,
    SEER,
    SAVER,
    HUNTER,
    WITCH,
    OLD_MAN,
    APPRENTICE_SEER,
    AURA_SEER,
    DISEASED,
    GHOST,
    MASON,
    MAYOR,
    PACIFIST,
    PI,
    PRIEST,
    PRINCE,
    SPELL_CASTER,
    TOUGH_GUY,
    TROUBLE_MAKER,
    IDIOT,
    VIRGINIA_WOOLF,
    // Đổi phe
    WILD_CHILD,
    CURSED,
    CULT_LEADER,
    DOPPEL_GANGER,
    DRUNK,
    HOODLUM,
    ILLUMINATI,
    TANNER,
    VAMPIRE,
    //Phe sói
    WEREWOLF,
    WOLF_PLUS,
    FANG_FACE,
    DIRE_WOLF,
    FRUIT_WOLF,
    LONE_WOLF,
    MINION,
    SORCERESS,
    WOLVERINE,
    WOLF_CUB,
    ALPHA_WOLF
}

export enum PARTY {
    VILLAGER,
    BETRAYER, // Những kẻ phản bội
    WEREWOLF
}

// map các role với phe tương ứng
export const ROLE_PARTY: {[party in PARTY]: Roles[]} = {
    [PARTY.VILLAGER]: [
        Roles.VILLAGER,
        Roles.OLD_MAN,
        Roles.WITCH,
        Roles.SEER,
        Roles.SAVER,
        Roles.HUNTER,
        Roles.CUPID,
        Roles.LYCAN,
        Roles.ANGEL,
        Roles.APPRENTICE_SEER,
        Roles.AURA_SEER,
        Roles.DISEASED,
        Roles.GHOST,
        Roles.IDIOT,
        Roles.MASON,
        Roles.MAYOR,
        Roles.PACIFIST,
        Roles.VIRGINIA_WOOLF,
        Roles.PI,
        Roles.PRIEST,
        Roles.PRINCE,
        Roles.SPELL_CASTER,
        Roles.TOUGH_GUY,
        Roles.TROUBLE_MAKER
    ],
    [PARTY.BETRAYER]: [
        Roles.WILD_CHILD,
        Roles.CURSED,
        Roles.DOPPEL_GANGER,
        Roles.DRUNK,
        Roles.CULT_LEADER,
        Roles.HOODLUM,
        Roles.TANNER,
        Roles.VAMPIRE,
        Roles.ILLUMINATI
    ],
    [PARTY.WEREWOLF]: [
        Roles.WEREWOLF,
        Roles.WOLF_PLUS,
        Roles.SORCERESS,
        Roles.LONE_WOLF,
        Roles.WOLF_CUB,
        Roles.MINION,
        Roles.DIRE_WOLF,
        Roles.ALPHA_WOLF,
        Roles.FRUIT_WOLF,
        Roles.FANG_FACE,
        Roles.WOLVERINE
    ]
};
// Dùng phía server, không xoá
export const ROLE_NAMES: {[role in Roles]: string} = {
    // PHE SÓI
    [Roles.WEREWOLF]: "SÓI",
    [Roles.CURSED]: "BÁN SÓI",
    [Roles.WOLF_PLUS]: "SÓI NGUYỀN",
    [Roles.WILD_CHILD]: "CON HOANG",
    // PHE DÂN
    [Roles.SEER]: "TIÊN TRI",
    [Roles.SAVER]: "BẢO VỆ",
    [Roles.HUNTER]: "THỢ SĂN",
    [Roles.VILLAGER]: "DÂN",
    [Roles.WITCH]: "PHÙ THỦY",
    [Roles.OLD_MAN]: "GIÀ LÀNG",
    [Roles.CUPID]: "THẦN TÌNH YÊU",
    [Roles.LYCAN]: "NGƯỜI HÓA SÓI",
    [Roles.ANGEL]: "THIÊN SỨ",
    [Roles.ALPHA_WOLF]: "",
    [Roles.APPRENTICE_SEER]: "",
    [Roles.AURA_SEER]: "",
    [Roles.CULT_LEADER]: "",
    [Roles.DIRE_WOLF]: "",
    [Roles.DISEASED]: "",
    [Roles.DOPPEL_GANGER]: "",
    [Roles.DRUNK]: "",
    [Roles.FANG_FACE]: "",
    [Roles.FRUIT_WOLF]: "",
    [Roles.GHOST]: "",
    [Roles.HOODLUM]: "",
    [Roles.ILLUMINATI]: "",
    [Roles.LONE_WOLF]: "",
    [Roles.MASON]: "",
    [Roles.MAYOR]: "",
    [Roles.MINION]: "",
    [Roles.PACIFIST]: "",
    [Roles.PI]: "",
    [Roles.PRIEST]: "",
    [Roles.PRINCE]: "",
    [Roles.SORCERESS]: "",
    [Roles.SPELL_CASTER]: "",
    [Roles.TANNER]: "",
    [Roles.TOUGH_GUY]: "",
    [Roles.TROUBLE_MAKER]: "",
    [Roles.VAMPIRE]: "",
    [Roles.IDIOT]: "",
    [Roles.VIRGINIA_WOOLF]: "",
    [Roles.WOLF_CUB]: "",
    [Roles.WOLVERINE]: ""
};
// Dùng cho chatbot của DUY
export const ROLE_IMAGES: {[role: number]: string} = {
    // PHE SÓI
    [Roles.WEREWOLF]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278418034541",
    [Roles.CURSED]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278411367875",
    [Roles.WOLF_PLUS]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1897745170521199",
    // PHE DÂN
    [Roles.SEER]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278528034530",
    [Roles.SAVER]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278331367883",
    [Roles.HUNTER]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278518034531",
    [Roles.VILLAGER]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278298034553",
    [Roles.WITCH]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278464701203‍",
    [Roles.OLD_MAN]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278381367878",
    [Roles.CUPID]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1889278324701217",
    [Roles.LYCAN]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1891874781108238",
    [Roles.ANGEL]: "https://www.facebook.com/masoibot/photos/pcb.1889279921367724/1903763679919348‍"
};
export const ROLE_MAX: {[role in Roles]: number} = {
    // PHE SÓI
    [Roles.WEREWOLF]: 10,
    [Roles.CURSED]: 1,
    [Roles.WOLF_PLUS]: 1,
    [Roles.WILD_CHILD]: 1,
    // PHE DÂN
    [Roles.SEER]: 1,
    [Roles.SAVER]: 1,
    [Roles.HUNTER]: 1,
    [Roles.VILLAGER]: 10,
    [Roles.WITCH]: 1,
    [Roles.OLD_MAN]: 1,
    [Roles.CUPID]: 1,
    [Roles.LYCAN]: 10,
    [Roles.ANGEL]: 1,
    // ROLE CHUA HOAT DONG
    [Roles.ALPHA_WOLF]: 0,
    [Roles.APPRENTICE_SEER]: 0,
    [Roles.AURA_SEER]: 0,
    [Roles.CULT_LEADER]: 0,
    [Roles.DIRE_WOLF]: 0,
    [Roles.DISEASED]: 0,
    [Roles.DOPPEL_GANGER]: 0,
    [Roles.DRUNK]: 0,
    [Roles.FANG_FACE]: 0,
    [Roles.FRUIT_WOLF]: 0,
    [Roles.GHOST]: 0,
    [Roles.HOODLUM]: 0,
    [Roles.ILLUMINATI]: 0,
    [Roles.LONE_WOLF]: 0,
    [Roles.MASON]: 0,
    [Roles.MAYOR]: 0,
    [Roles.MINION]: 0,
    [Roles.PACIFIST]: 0,
    [Roles.PI]: 0,
    [Roles.PRIEST]: 0,
    [Roles.PRINCE]: 0,
    [Roles.SORCERESS]: 0,
    [Roles.SPELL_CASTER]: 0,
    [Roles.TANNER]: 0,
    [Roles.TOUGH_GUY]: 0,
    [Roles.TROUBLE_MAKER]: 0,
    [Roles.VAMPIRE]: 0,
    [Roles.IDIOT]: 0,
    [Roles.VIRGINIA_WOOLF]: 0,
    [Roles.WOLF_CUB]: 0,
    [Roles.WOLVERINE]: 0
};

export const AVAILABLE_ROLES = Object.keys(Roles)
    .slice(0, Object.keys(Roles).length / 2)
    .map((str) => parseInt(str) as Roles);

export const ROLE_POINT: {[role in Roles]: number} = {
    [Roles.WILD_CHILD]: -2,
    // PHE SÓI
    [Roles.WEREWOLF]: -6,
    [Roles.CURSED]: -3,
    [Roles.WOLF_PLUS]: -9,
    // PHE DÂN
    [Roles.SEER]: +7,
    [Roles.SAVER]: +3,
    [Roles.HUNTER]: +3,
    [Roles.VILLAGER]: +1,
    [Roles.WITCH]: +4,
    [Roles.OLD_MAN]: +2,
    [Roles.CUPID]: -3,
    [Roles.LYCAN]: -1,
    [Roles.ANGEL]: 0,
    [Roles.ALPHA_WOLF]: -9,
    [Roles.APPRENTICE_SEER]: +4,
    [Roles.AURA_SEER]: +3,
    [Roles.CULT_LEADER]: 1,
    [Roles.DIRE_WOLF]: -4,
    [Roles.DISEASED]: 3,
    [Roles.DOPPEL_GANGER]: -2,
    [Roles.DRUNK]: 4,
    [Roles.FANG_FACE]: -5,
    [Roles.FRUIT_WOLF]: -3,
    [Roles.GHOST]: 2,
    [Roles.HOODLUM]: 0,
    [Roles.ILLUMINATI]: -3,
    [Roles.LONE_WOLF]: -5,
    [Roles.MASON]: 2,
    [Roles.MAYOR]: 2,
    [Roles.MINION]: -6,
    [Roles.PACIFIST]: -1,
    [Roles.PI]: 3,
    [Roles.PRIEST]: 3,
    [Roles.PRINCE]: 3,
    [Roles.SORCERESS]: -3,
    [Roles.SPELL_CASTER]: 1,
    [Roles.TANNER]: -2,
    [Roles.TOUGH_GUY]: 3,
    [Roles.TROUBLE_MAKER]: -3,
    [Roles.VAMPIRE]: -7,
    [Roles.IDIOT]: 2,
    [Roles.VIRGINIA_WOOLF]: -2,
    [Roles.WOLF_CUB]: -8,
    [Roles.WOLVERINE]: -4
};
