import {Roles} from "../Roles";

export const ROLE_REQUIRE_ROLES: {[r in Roles]: Roles[]} = {
    [Roles.WILD_CHILD]: [],
    [Roles.WEREWOLF]: [],
    [Roles.CURSED]: [],
    [Roles.WOLF_PLUS]: [],
    [Roles.SEER]: [],
    [Roles.SAVER]: [],
    [Roles.HUNTER]: [],
    [Roles.VILLAGER]: [],
    [Roles.WITCH]: [],
    [Roles.OLD_MAN]: [],
    [Roles.CUPID]: [],
    [Roles.LYCAN]: [Roles.SEER],
    [Roles.ANGEL]: [],
    [Roles.ALPHA_WOLF]: [],
    [Roles.APPRENTICE_SEER]: [Roles.SEER],
    [Roles.AURA_SEER]: [],
    [Roles.CULT_LEADER]: [],
    [Roles.DIRE_WOLF]: [],
    [Roles.DISEASED]: [],
    [Roles.DOPPEL_GANGER]: [],
    [Roles.DRUNK]: [],
    [Roles.FANG_FACE]: [],
    [Roles.FRUIT_WOLF]: [],
    [Roles.GHOST]: [],
    [Roles.HOODLUM]: [],
    [Roles.ILLUMINATI]: [],
    [Roles.LONE_WOLF]: [],
    [Roles.MASON]: [],
    [Roles.MAYOR]: [],
    [Roles.MINION]: [],
    [Roles.PACIFIST]: [],
    [Roles.PI]: [],
    [Roles.PRIEST]: [],
    [Roles.PRINCE]: [],
    [Roles.SORCERESS]: [Roles.SEER],
    [Roles.SPELL_CASTER]: [],
    [Roles.TANNER]: [],
    [Roles.TOUGH_GUY]: [],
    [Roles.TROUBLE_MAKER]: [],
    [Roles.VAMPIRE]: [],
    [Roles.IDIOT]: [],
    [Roles.VIRGINIA_WOOLF]: [],
    [Roles.WOLF_CUB]: [],
    [Roles.WOLVERINE]: []
};

export const ROLE_REQUIRE_MIN_PLAYER: {[r in Roles]: number} = {
    [Roles.WEREWOLF]: 4,
    [Roles.VILLAGER]: 4,
    [Roles.SEER]: 4,
    [Roles.SAVER]: 4,
    [Roles.HUNTER]: 5,
    [Roles.CURSED]: 5,
    [Roles.LYCAN]: 5,
    [Roles.WITCH]: 6,
    [Roles.CUPID]: 6,
    [Roles.WILD_CHILD]: 6,
    [Roles.ANGEL]: 7,
    [Roles.OLD_MAN]: 7,
    [Roles.WOLF_PLUS]: 7,
    [Roles.TOUGH_GUY]: 8,
    [Roles.TANNER]: 8,
    [Roles.SPELL_CASTER]: 8,
    [Roles.TROUBLE_MAKER]: 8,
    [Roles.VAMPIRE]: 8,
    [Roles.IDIOT]: 8,
    [Roles.ALPHA_WOLF]: 10,
    [Roles.APPRENTICE_SEER]: 10,
    [Roles.AURA_SEER]: 10,
    [Roles.CULT_LEADER]: 10,
    [Roles.DIRE_WOLF]: 10,
    [Roles.DISEASED]: 10,
    [Roles.DOPPEL_GANGER]: 10,
    [Roles.MASON]: 10,
    [Roles.DRUNK]: 10,
    [Roles.FANG_FACE]: 10,
    [Roles.FRUIT_WOLF]: 10,
    [Roles.GHOST]: 10,
    [Roles.HOODLUM]: 10,
    [Roles.LONE_WOLF]: 10,
    [Roles.MAYOR]: 10,
    [Roles.MINION]: 10,
    [Roles.PACIFIST]: 10,
    [Roles.PI]: 10,
    [Roles.PRIEST]: 10,
    [Roles.PRINCE]: 10,
    [Roles.SORCERESS]: 10,
    [Roles.VIRGINIA_WOOLF]: 10,
    [Roles.WOLF_CUB]: 10,
    [Roles.WOLVERINE]: 10,
    [Roles.ILLUMINATI]: 15
};

export const BASE_ROLE_1 = [Roles.VILLAGER];
export const BASE_ROLE_2 = [...BASE_ROLE_1, Roles.SEER];
export const BASE_ROLE_3 = [...BASE_ROLE_2, Roles.SAVER];
export const BASE_ROLE_4 = [...BASE_ROLE_3, Roles.HUNTER];
export const BASE_ROLE_5 = [...BASE_ROLE_4, Roles.CUPID];
export const BASE_ROLE_6 = [...BASE_ROLE_5, Roles.OLD_MAN];
export const BASE_ROLE_7 = [...BASE_ROLE_6, Roles.WITCH];
export const BASE_ROLE_8 = [...BASE_ROLE_7, Roles.CURSED];
export const BASE_ROLE_9 = [...BASE_ROLE_8, Roles.WILD_CHILD];
export const BASE_ROLE_10 = [...BASE_ROLE_9, Roles.LYCAN];

export const GAME_PLAYERS_REQUIRE_ROLES: {[numOfPlayer: number]: Roles[]} = {
    [4]: BASE_ROLE_1,
    [5]: BASE_ROLE_2,
    [6]: BASE_ROLE_3,
    [7]: BASE_ROLE_4,
    [8]: BASE_ROLE_4,
    [9]: BASE_ROLE_4,
    [10]: BASE_ROLE_4,
    [11]: BASE_ROLE_5,
    [12]: BASE_ROLE_6,
    [13]: BASE_ROLE_6,
    [14]: BASE_ROLE_6,
    [15]: BASE_ROLE_7,
    [16]: BASE_ROLE_7,
    [17]: BASE_ROLE_8,
    [18]: BASE_ROLE_8,
    [19]: BASE_ROLE_9,
    [20]: BASE_ROLE_8
};
