// map các role với phe tương ứng
import {Roles} from "../enums";

export const ROLE_MAX: {[role in Roles]: number} = {
    // PHE SÓI
    [Roles.WEREWOLF]: 9, // Game tối đa có 20 người -> số sói < 10
    [Roles.CURSED]: 1,
    [Roles.WOLF_PLUS]: 1,
    [Roles.WILD_CHILD]: 1,
    // PHE DÂN
    [Roles.SEER]: 1,
    [Roles.SAVER]: 1,
    [Roles.HUNTER]: 1,
    [Roles.VILLAGER]: 19, // Game tối đa 20 người, phải có ít nhất 1 sói
    [Roles.WITCH]: 1,
    [Roles.OLD_MAN]: 1,
    [Roles.CUPID]: 1,
    [Roles.LYCAN]: 4,
    [Roles.ANGEL]: 1,
    // ROLE CHUA HOAT DONG
    [Roles.ALPHA_WOLF]: 0,
    [Roles.APPRENTICE_SEER]: 0,
    [Roles.AURA_SEER]: 0,
    [Roles.CULT_LEADER]: 0,
    [Roles.DIRE_WOLF]: 0,
    [Roles.DISEASED]: 0,
    [Roles.DOPPEL_GANGER]: 0,
    [Roles.DRUNK]: 0,
    [Roles.FANG_FACE]: 0,
    [Roles.FRUIT_WOLF]: 0,
    [Roles.GHOST]: 0,
    [Roles.HOODLUM]: 0,
    [Roles.ILLUMINATI]: 0,
    [Roles.LONE_WOLF]: 0,
    [Roles.MASON]: 0,
    [Roles.MAYOR]: 0,
    [Roles.MINION]: 0,
    [Roles.PACIFIST]: 0,
    [Roles.PI]: 0,
    [Roles.PRIEST]: 0,
    [Roles.PRINCE]: 0,
    [Roles.SORCERESS]: 0,
    [Roles.SPELL_CASTER]: 0,
    [Roles.TANNER]: 0,
    [Roles.TOUGH_GUY]: 0,
    [Roles.TROUBLE_MAKER]: 0,
    [Roles.VAMPIRE]: 0,
    [Roles.IDIOT]: 0,
    [Roles.VIRGINIA_WOOLF]: 0,
    [Roles.WOLF_CUB]: 0,
    [Roles.WOLVERINE]: 0
};
export const ROLE_POINT: {[role in Roles]: number} = {
    [Roles.WILD_CHILD]: -2,
    // PHE SÓI
    [Roles.WEREWOLF]: -6,
    [Roles.CURSED]: -2,
    [Roles.WOLF_PLUS]: -9,
    // PHE DÂN
    [Roles.SEER]: 3,
    [Roles.SAVER]: 3,
    [Roles.HUNTER]: 3,
    [Roles.VILLAGER]: 1,
    [Roles.WITCH]: 5,
    [Roles.OLD_MAN]: 4,
    [Roles.CUPID]: 3,
    [Roles.LYCAN]: -1,
    [Roles.ANGEL]: 1,
    [Roles.ALPHA_WOLF]: -9,
    [Roles.APPRENTICE_SEER]: +4,
    [Roles.AURA_SEER]: +3,
    [Roles.CULT_LEADER]: 1,
    [Roles.DIRE_WOLF]: -4,
    [Roles.DISEASED]: 3,
    [Roles.DOPPEL_GANGER]: -2,
    [Roles.DRUNK]: 4,
    [Roles.FANG_FACE]: -5,
    [Roles.FRUIT_WOLF]: -3,
    [Roles.GHOST]: 2,
    [Roles.HOODLUM]: 0,
    [Roles.ILLUMINATI]: -3,
    [Roles.LONE_WOLF]: -5,
    [Roles.MASON]: 2,
    [Roles.MAYOR]: 2,
    [Roles.MINION]: -6,
    [Roles.PACIFIST]: -1,
    [Roles.PI]: 3,
    [Roles.PRIEST]: 3,
    [Roles.PRINCE]: 3,
    [Roles.SORCERESS]: -3,
    [Roles.SPELL_CASTER]: 1,
    [Roles.TANNER]: -2,
    [Roles.TOUGH_GUY]: 3,
    [Roles.TROUBLE_MAKER]: -3,
    [Roles.VAMPIRE]: -7,
    [Roles.IDIOT]: 2,
    [Roles.VIRGINIA_WOOLF]: -2,
    [Roles.WOLF_CUB]: -8,
    [Roles.WOLVERINE]: -4
};
